### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AIPTU** [JavierLeon9966/EntityMonitor#1]
Can find entity or tile class or named, and maybe clear specific entity or tile?

**Comment by JavierLeon9966** [comment]
This plugin only tells you the count, not the most entities or tiles with their respective names and it doesn’t clear any of those

**Comment by AIPTU** [comment]
> This plugin only tells you the count, not the most entities or tiles with their respective names and it doesn’t clear any of those

That's why I made this request, I think it's useful for entity monitor
